// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tceltaaatpowkzlxgzhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjZWx0YWFhdHBvd2t6bHhnemhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzcwODAsImV4cCI6MjA2ODM1MzA4MH0.NP1ohjWKCwTBQWC8NAW4C1zL40C4cfn4ZeVzx0DGpGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});